name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: ations/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: ${{secrets.envkey_POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: "students_test"
          envkey_POSTGRES_URL: ${{secrets.envkey_POSTGRES_URL}}
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app_students npm run test
      - name: Build
        run: npm i && npm run build
